### ISSUE TITLE
AppVeyor CI

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#3] opened 2017-08-28 17:06 UTC
AppVeyor ships 3 images (see [here](https://www.appveyor.com/docs/build-environment/#pre-installed-software)):
- VS 2013. MinGW and Cygwin pre-installed
- VS 2015. MinGW and Cygwin pre-installed
- VS 2017. Only Cygwin pre-installed

We should use all three images, because:
- CMake 3.0 supports VS 2013, at most.
- CMake 3.9 supports all three of them.

However, I am not sure about MinGW _vs._ Cygwin. Should we try to use both? Or just one of the two?

**Comment by bast** [comment] 2017-08-28 20:51
I think it would be cool if we manage to use both, then we cover a wide spectrum. If we have to choose one, then I am not even sure which one is more common :-)

**Comment by robertodr** [comment] 2017-08-29 07:03
https://stackoverflow.com/questions/771756/what-is-the-difference-between-cygwin-and-mingw

**Comment by bast** [comment] 2017-08-29 22:07
Excellent! Let's do it. I will soon start lifting some weight here. Thanks for all the work.

**Comment by bast** [comment] 2018-02-23 14:23
Can we close this? The problem is not solved but I think we should create smaller issues from here on for Appveyor problems.

**Comment by robertodr** [comment] 2018-02-23 15:01
Let's close this. I have a smaller example that works with AppVeyor and we can build up from there.

**Closed** 2018-02-23 15:03 UTC
